"""
Write a generator function that yields square numbers up to N
"""


def generate_square_numbers(limit: int):
    """
    Generate square numbers from 1 to N
    """
    for number in range(1, limit + 1):
        yield number ** 2


def print_square_numbers() -> None:
    """
    Print square numbers generated by a generator
    """
    try:
        limit = int(input("Enter the limit: "))
        if limit < 1:
            raise ValueError("Limit must be a positive integer")

        for square in generate_square_numbers(limit):
            print(square)

    except ValueError:
        print("Invalid input. Please enter a positive integer")


if __name__ == "__main__":
    print_square_numbers()