spring.application.name=restaurant-order-portal

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_portal_db
spring.datasource.username=
spring.datasource.password=

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#secret key
jwt.secret=dummy_secret_key