spring.application.name=restaurant-order-portal
spring.profiles.active=local

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_portal_db
spring.datasource.username=
spring.datasource.password=

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#secret key
jwt.secret=dummy_secret_key

#file uploads access
spring.web.resources.static-locations=file:uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB